book_shelf/urls.py
from django.urls import path#, include, my_loan_book
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('author_index/', views.author_index, name='author_index'),
        #List and Detail views
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genres/<int:pk>', views.Book_by_Genre, name='genre-detail'),
    path('languages/', views.LanguageListView.as_view(), name='languages'),
    path('languages/<int:pk>', views.LanguageDetailView.as_view(), name='language-detail'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('brbooks/', views.LoanedBooks_ByUserListView.as_view(), name='br-books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
        #Create, Update and Delete views
    path('bookinstance/(?P<pk>\d+)/$', views.BookInstanceUpdate.as_view(), name='bookinstance_update'),
    path(r'^bookinstance/(?P<pk>\d+)/$', views.create_book_instances, name='bookinstance_create'),
    path('author/create/', views.AuthorCreate, name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('genre/create/', views.GenreCreate, name='genre_create'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(), name='genre_update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(), name='genre_delete'),
    path('language/create/', views.LanguageCreate, name='language_create'),
    path('language/<int:pk>/update/', views.LanguageUpdate.as_view(), name='language_update'),
    path('language/<int:pk>/delete/', views.LanguageDelete.as_view(), name='language_delete'),
    path('book/create/', views.BookCreate, name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
        #Django Account view       #user views
    path('book/author/', views.book_authors, name='author'),
    path('book/stores/', views.book_stores, name='stores'),
    path(r'^stores/(?P<pk>\d+)/$', views.book_copies, name='copies'),
    path('applyforbook/<uuid:pk>/qeues/', views.applied_for_Book, name='qeues'),
    path('book/<uuid:pk>/approval/', views.BookLoanApproval, name='approval'),
    path('book/qeuing/', views.LoanedBooks_On_Qeue.as_view(), name='qeuing'),
    path('my_loan_book/', views.my_loan_book, name='my_loan_book'),
    path('book/<uuid:pk>/renew_qeues/', views.applied_for_Book_renew, name='renew_qeues'),
    path('book/renew/', views.renew_loan_book, name='renew_approval'),
    #path('book_copies/(?P<pk>\d+)/$', views.applied_for_Book_Intances, name='book_copies'),
]

uqi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/result/', permanent=True)),
    path('result/', include('result.urls')),
    path('book_shelf/', include('book_shelf.urls')),
    #url('^', include('django.contrib.auth.urls')),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:###for image upload
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_shelf/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date
# Create your models here.
########################################Genre model###############################################
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    def get_absolute_url(self):
        """Returns the url to access a detail record for this genre."""
        return reverse('genre-detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object."""
        return self.name
#############################################Language Model##################################################
class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")
    def get_absolute_url(self):
        """Returns the url to access a detail record for this language."""
        return reverse('language-detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name
########################################Book model###########################################################
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    no_of_copy = models.CharField(max_length=8, null=True, blank=True)
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    def display_genre(self):#Configure list views
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'

############################################BookInstance model#######################################################################

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True) 
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, default='9999-12-31')
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    renew = models.CharField(max_length=5, null=True, blank=True)
    LOAN_STATUS = (
        ('Maintenance', 'Maintenance'),
        ('On loan', 'On loan'),
        ('Available', 'Available'),
        ('Reserved', 'Reserved'),
    )

    status = models.CharField(
        max_length=13,
        choices=LOAN_STATUS,
        blank=True,
        default='Maintenance',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),) 
    
    
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

##################################################Author model################################################################
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100, help_text='Middle name inclusive.')
    last_name = models.CharField(max_length=100, help_text='Surname only.')
    date_of_birth = models.DateField(null=True, blank=True, default='9999-12-31')
    date_of_death = models.DateField('died', null=True, blank=True, default='9999-12-31')

    class Meta:
        ordering = ['last_name', 'first_name']
    
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

book_shelf/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from .models import Book, Author, BookInstance
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
    
class BookRenew(forms.Form):
    renewal_date = forms.CharField(max_length=5, help_text="Just type 'renew'")
    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        return data
    
class Author_form(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'date_of_birth', 'date_of_death',)
    
class Genre_form(forms.Form):
    name = forms.CharField(max_length=100, help_text="Just type-in the name.")
    def clean_renewal_date(self):
        data = self.cleaned_data['name']
        return data
    
class Book_form(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'genre', 'summary', 'isbn', 'language', 'no_of_copy',)
        
class BookInstanceForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ('imprint', 'status',)
    #name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Book Imprint here'}))
    #status = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Enter Book Status('Available') here or leave blanck for book on Maintenance"}))

book_shelf/templates/book_shelf/author-detail.html
{% extends "base_generic.html" %}
{% block content %}
 <div style="width:80%;margin-right:280px; font-size:11">
    <h4>Copies</h4>
    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

book_shelf/templates/book_shelf/author_detail.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
            <table style="width:80%;margin:1px; font-size:11">
                <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Author's Name: </strong><em style="font-family:Helvetica; color:white; font-size: 12px;">{{ author.first_name }}, {{ author.last_name }}</em></div>
                <ol>
                   <li><strong>Birth:</strong>{{ author.date_of_birth }}</em>--<em> <strong>Dirth:</strong>{{ author.date_of_death }}</em></li>
                   <li><strong>Author's Books:</strong></li>
                </ol>
                <thead>
                    <tr><th>Book(s)</th><th>Copies</th></tr>      
                </thead>
                <tbody>
                    {% if author.book_set.all %}
                    {% for book in author.book_set.all %}
                        <tr><td><a href="{% url 'book-detail' book.pk %}">{{book}}</a></td><td>{{book.bookinstance_set.all.count}}</td></tr>
                    {% endfor %}
                    {% else %}
                        <p>There are no books in shelf yet.</p>
                    {% endif %}      
                </tbody>
            </table>
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="fc">
      <em class="capt"><h6>New Author</h6></em>
    </div>
  <form action="" method="post" style="width:100%;margin-left: 30px; font-size:0.5">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" style="width:13.5%;margin-left: -53px; font-size:1">
  </form>
{% endblock %}

book_shelf/templates/book_shelf/book_authors.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
        <table style="width:80%;margin:1px; font-size:11">
            <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Authors</strong></div>
            <thead>
                <tr><th>Last-Name(s)</th><th>First-Name(s)</th><th>Birth(s)</th><th>Died(s)</th></tr>      
            </thead>
            <tbody>
                {% if book_authors %}
                {% for author in book_authors %}
                    <tr><td><a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a></td><td><a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a></td><td>{{author.date_of_birth}}</td><td>{{author.date_of_death}}</td></tr>
                {% endfor %}
                {% else %}
                    <p>There are no author in list yet.</p>
                {% endif %}      
            </tbody>
        </table>
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %} 
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/book_by_genre.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
            <table style="width:80%;margin:1px; font-size:11">
                <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Genre</strong></div>
                
                <thead>
                    <tr><th>Title(s)</th><th>Author(s)</th><th>ISBN(s)</th></tr>      
                </thead>
                <tbody>
                    {% if book_by_genre %}
                    {% for gen in book_by_genre %}
                        <tr><td>{{gen.title}}</td><td>{{gen.author}}</td><td><a href="{% url 'copies' pk=gen.id %}">{{gen.isbn}}</a></td></tr>
                    {% endfor %}
                    {% else %}
                        <p>There are no book for this genre yet.</p>
                    {% endif %}      
                </tbody>
            </table>
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/book_copies.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
            <table style="width:80%;margin:1px; font-size:11">
                <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Book Copie(s):</strong><em style="font-family:Helvetica; color:white; font-size: 12px;"> {{book_copies.count}}</em></div>
                <thead>
                    <tr><th>Book Title(s)</th><th>Imprint(s)</th><th>Statu(s)</th><th>Return-Date(s)</th><th>Edit-Book-Instance</th></tr>      
                </thead>
                <tbody>
                    {% if book_copies %}
                    {% for bookinst in book_copies %}
                        <tr class="{% if bookinst.is_overdue %}text-danger*!{% endif %}"><td><a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a></td><td>{{ bookinst.imprint }}</td><td><a href="{% url 'qeues' pk=bookinst.id %}">{{ bookinst.status }}</a></td><td>{{ bookinst.due_back }}</td><td><a href="{% url 'bookinstance_update' pk=bookinst.id %}"><span class="glyphicon glyphicon-edit"> admin</span></a></strong></strong></a></td></tr>
                    {% endfor %}
                    {% else %}
                        <p>There are no borrowed-book in your list yet.</p>
                    {% endif %}      
                </tbody>
            </table>
            {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
            {% endblock %}
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/book_renew.html
{% extends "base_generic.html" %}
{% block content %}
  <div class="fc">
      <div class="capt">Renew: <em style="font-family:Helvetica; color:white; font-size: 12px;"> {{ book_renew.book.title }}</em></div>
    </div>
  <ol>
     <li><strong>Renew:</strong> <em>{{ book_renew.book.title }}</em></li>
     <li><strong>Borrower:</strong> <em>{{ book_renew.borrower }}</em></li>
  </ol>
  <div {% if book_renew.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_renew.due_back }}</div>
    
  <form action="" method="post" style="width:100%;margin-left: 30px; font-size:0.5">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" style="width:13.5%;margin-left: -53px; font-size:1">
  </form>
{% endblock %}

book_shelf/templates/book_shelf/book_stores.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
        <table style="width:80%;margin:1px; font-size:11">
            <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Books on Shelf </strong></div>
            <thead>
                <tr><th>Title(s)</th><th>Author(s)</th><th>ISBN(s)</th><th>Language(s)</th><th>DI(s)</th></tr>      
            </thead>
            <tbody>
                {% if book_stores %}
                {% for book in book_stores %}
                    <tr><td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td><td><a href="{% url 'author_update' pk=book.author.id %}">{{book.author}}</a></td><td><a href="{% url 'copies' pk=book.id %}">{{ book.isbn }}</a></td><td><a href="{% url 'language_update' pk=book.language.id %}">{{ book.language }}</a></td><td><a href="{% url 'book_update' pk=book.id %}">{{ book.no_of_copy }}</a></td></tr>
                {% endfor %}
                {% else %}
                    <p>There are no books in store yet.</p>
                {% endif %}      
            </tbody>
        </table>
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %} 
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/bookinstance_list_2.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
            <table style="width:80%;margin:1px; font-size:11">
                <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Book </strong><em>Status</em></div>
                <thead>
                    <tr><th>Title(s)</th><th>Imprint(s)</th><th>Status(s)</th></tr>      
                </thead>
                <tbody>
                    {% if bookinstance_list %}
                    {% for bookinst in bookinstance_list %}
                        <tr class="{% if bookinst.is_overdue %}text-danger*!{% endif %}"><td><a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a></td><td>{{ bookinst.imprint }}</td><td>{{ bookinst.status }}</td></tr>
                    {% endfor %}
                    {% else %}
                        <p>There are no borrowed-book in your list yet.</p>
                    {% endif %}      
                </tbody>
            </table>
            {% block pagination %}
            {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
            {% endif %}
            {% endblock %}
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/bookinstance_list_borrowed_to_users.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
        <table style="width:80%;margin:1px; font-size:11">
            <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Borrowed books by users</strong></div>
            <thead>
                <tr><th>Title(s)</th><th>Return-Date(s)</th><th>Borrower(s)</th><th>Renew(s)</th></tr>      
            </thead>
            <tbody>
                {% if bookinstance_list %}
                {% for bookinst in bookinstance_list %}
                    <tr class="{% if bookinst.is_overdue %}text-danger*!{% endif %}"><td><a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a></td><td>{{ bookinst.due_back }}</td><td>{{ bookinst.borrower }}</td><td>{% if perms.book_shelf.can_mark_returned %}<a href="{% url 'renew-book-librarian' bookinst.id %}"><span class="glyphicon glyphicon-edit"></span></a>{% endif %}</td></tr>
                {% endfor %}
                {% else %}
                    <p>There are no auther in list yet.</p>
                {% endif %}      
            </tbody>
        </table>
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %} 
    </body>
    {% endblock %}
</html>

book_shelf/templates/book_shelf/create_book_instance.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container text-center">
<br><p style="width:40%;margin-left: 0px; font-size:12">Book Instance Creation Form!</p>
<div class='signup' style="width:50%;margin-left: 0px; font-size:12">
<form method="post" style="width:80%;margin-left:89; font-size:11;">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    {% csrf_token %}
    <div class="row">
      <div class="col-xs-6">
        {{ form.imprint|as_crispy_field }}
      </div>
      <div class="col-xs-6">
        {{ form.status|as_crispy_field }}
      </div>
    </div> 
    {% endfor %}
    <div style="width:97%;margin-left: 10px; font-size:1">create new |<a href="{% url 'book_create' %}" target=_blank >Book</a>|<a href="{% url 'language_create' %}" target=_blank >Language</a>|<a href="{% url 'author_create' %}" target=_blank >Author</a>|<a href="{% url 'genre_create' %}" target=_blank >genre</a>| one-time!</div>
    <div class="row spacer">
    <div class="col-4 offset-2" style="width:97%;margin-left: 10px; font-size:1">
        <button type="submit" class="btn btn-block btn-primary">Create</button>
    </div>
</div>
  </form>
</div>
{% endblock %}

book_shelf/templates/book_shelf/genre_form.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="fc">
      <em class="capt"><h6>New Genre</h6></em>
    </div>
  <form action="" method="post" style="width:100%;margin-left: 30px; font-size:0.5">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" style="width:13.5%;margin-left: -53px; font-size:1">
  </form>
{% endblock %}

book_shelf/templates/book_shelf/language_form.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="fc">
      <em class="capt"><h6>New Genre</h6></em>
    </div>
  <form action="" method="post" style="width:100%;margin-left: 30px; font-size:0.5">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" style="width:13.5%;margin-left: -53px; font-size:1">
  </form>
{% endblock %}

book_shelf/templates/book_shelf/language_list.html
<!DOCTYPE html>
{% extends "base_generic.html" %}
<html>
    {% block content %}
    <head>

    </head>
    <body>
        <table style="width:80%;margin:1px; font-size:11">
            <div class="capt" style="width:80%;margin:1px; font-size:21"><strong>Languages</strong></div>
            <tbody>
                {% if language_list %}
                {% for lang in language_list %}
                    <tr><td><a href="{{ lang.get_absolute_url }}">{{ lang.name }}</a></td>{% if perms.catalog.can_mark_returned %}<td><a href="{% url 'language_update' lang.id %}"><span class="glyphicon glyphicon-edit"></span></a></td><td><a href="{% url 'language_delete' lang.id %}"><span class="glyphicon glyphicon-remove"></span></a></td>{% endif %}</tr>
                {% endfor %}
                {% else %}
                    <p>There are no language in list yet.</p>
                {% endif %}      
            </tbody>
        </table>
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    <div>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</div>
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
        {% endblock %} 
    </body>
    {% endblock %}
</html>